- data/data.go
- go.mod
- go.sum
- models/models.go
- Add structs in models.go
- Used Timestamp package
> Added structs in models/models.go and created data/data.go

- .gitignore
- Dockerfile
- Makefile
- kubernetes/merauction.yml
- kubernetes/mongodb.yml
> Add k8s manifest files for merauction app and mongodb

- models/models.go
- Added list of interests to the user struct type in order for us to save users interest tags and show them a personalized dashboard.
this solves #39
> added interest list to user struct type

- models/models.go
- added a list of Tag to the auction struct in order to save the tags for every image uploaded by the user (tags extracted using CAP-THAT-PIC)
- added BasePrice to the struct in order to have a base price logic for every item auctioned on the website
this solves #40
> Change auction struct

- models/models.go
- added a count to the Bid struct in order to keep track of bids made by a particular user (UserID) in a auction (AuctionID)
this solves #46
> Change bid struct

- Makefile
- kubernetes/merauction.yml
Redeploy to kouzoh-p-s-liu/merauc-cluster-1
By command
`make docker`
`make kubernetes-build`
this solves #50
> Redeployment done

- .circleci/config.yml
- testing the CI/CD pipeline
- made changes to the image name
> changes to image name

- templates/create_auction/index.tmpl
- split the base64 image string to just grab the base64 url and not the image type info in front of it.
- the image type is already in the card.tmpl img src
> Frontend create auction

- server/server_test.go
> Add test for getDescriptionfromImage and getTagsfromImage

- templates/auction/details.tmpl
- templates/auction_list/index.tmpl
- templates/create_auction/index.tmpl
- looping over the array of images to show image on the auction details page
> Auction details page

- templates/common/navbar.tmpl
> Navbar routing

- templates/common/navbar.tmpl
- templates/create_auction/index.tmpl
> Timeout redirect

- templates/auction/index.tmpl
- error handling
- retrieving correct price, userid and time of bid placed
this resolved #110
> error handling and resolved bug of showing bids in frontend

- Makefile
- kubernetes/merauction.yml
- templates/create_auction/index.tmpl
> Remove quotes and \n from description

- server/handlers.go
- templates/auction/index.tmpl
- templates/create_auction/form.tmpl
- templates/create_auction/index.tmpl
- showing created by on every auction page, resolved the bug
> Added createdby

- data/data.go
- db/db.go
- server/handlers.go
- server/routes.go
- templates/common/navbar.tmpl
- Users can enter tag and search auctions now!!
> Add search by tag endpoint

- templates/auction/details.tmpl
- templates/auction_list/card.tmpl
- showing base price on cards on dashboard and in auction details page
this solves #104
> add-base-price-to-cards

- static/css/style.css
- templates/common/navbar.tmpl
- tooltip added when a user hover on the create auction button
> added tooltip for create auction button

- static/css/style.css
- added shadow on hover over cards in dashboard
> Cards styling

- static/css/style.css
- templates/create_auction/form.tmpl
- removed the label overlap with tags and description
> Create auction styling

- templates/create_auction/form.tmpl
- templates/create_auction/index.tmpl
- Change the display of tags in auctions create page
> Change the display of tags

- templates/auction_list/index.tmpl
- templates/common/navbar.tmpl
> Fix 404 and blank page problem
